server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/job_data?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456ppoo
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: auto

bailian:
  apiKey: ${AI_DASHSCOPE_API_KEY}
  baseUrl: "https://dashscope.aliyuncs.com/compatible-mode/v1/chat/completions"
  model: "qwen3.5-omni-plus-2026-03-15"
  timeoutMs: 60000
